Fix invalid link to compatibility-with-default-change-detection
dart-lang/angular pull request #1930
Opened 2020-10-19 10:26 UTC by lukaszkolodziejczyk

2020-10-19 12:58 UTC, lukaszkolodziejczyk commented
https://github.com/dart-lang/angular/issues/1928

2020-10-19 14:16 UTC, kevmoo approved these changes

2020-10-19 14:18 UTC, kevmoo requested changes
When making the first commit in a package after release, make sure to bump the version and add `-dev`

So `angular_compiler` should be at `1.0.1-dev` now in pubspec.yaml

Also add a corresponding entry to the changelog

2020-10-19 15:36 UTC, lejard-h commented
So there is no explanation on how to fix that kind of warning ?

Except use `OnPush` strategy everywhere ?

2020-10-20 14:04 UTC, kevmoo approved these changes

2020-10-20 14:55 UTC, merged